language: perl
matrix:
    fast_finish: true
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    - RELEASE_TESTING
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm -n Date::Utility" 
    - "cpanm -n Test::Mock::Redis"
    - "cpanm -n Test::PostgreSQL"
    - "cpanm -n DBI"
    - "cpanm -n Moose"
    - "cpanm -n JSON"
    - "cpanm -qn Test::Requires::Git"
    - "cpanm -qn Devel::Cover::Report::Codecov"
script:
    perl Makefile.PL && RELEASE_TESTING=1 make test
after_success:
    RELEASE_TESTING=1 cover -test -report codecov
