language: perl
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    - RELEASE_TESTING
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm Date::Utility" 
    - "cpanm Test::Mock::Redis"
    - "cpanm Test::PostgreSQL"
    - "cpanm DBI"
    - "cpanm Moose"
    - "cpanm JSON"
script:
  perl Makefile.PL && make test
